### PR TITLE
Docs: Add container class & rebuild docs

### PR DESCRIPTION
**Pull request by paulathevalley**
- Add `.Container` class to `static-index.jsx`
- Rebuild docs 

screen shot 2015-12-03 at 11 14 45 am

/cc @boygirl

### CODE REVIEW

**Comment by boygirl** [comment]
@paulathevalley seems like this PR deletes rather than modifies `doc/build/index.html` rebuild?

**Comment by paulathevalley** [comment]
Weird! I will try `npm run build-static-docs` again.

**Comment by boygirl** [comment]
beat you to the punch. My curiosity got the better of me

**Comment by paulathevalley** [comment]
That looks way better!

**Pull request merged**
