### PR TITLE
refactor pie to match other components

### PR DESCRIPTION
**Pull request by boygirl**
cc/ @angelanicholas cc/ @colinmegill 

This PR refactors pie so that the API is more similar to what's going on in other components. The biggest change was adding a style prop to replace props like `width` and `labelPadding`

### CODE REVIEW

**Comment by boygirl** [comment]
cc/ @exogen I had to change where `propTypes` and `defaultProps` were defined to get ecology docs to work properly. I declared them with `const` at the top of the file for readability.

**Comment by exogen** [comment]
Re: `propTypes` & `defaultProps` it seems like we should lean towards fixing ecology instead? `static` is the syntax people are going to use, it's even mentioned in the official React docs.

**Comment by exogen** [comment]
@boygirl It looks like updating `react-docgen` to the latest 2.4 release fixes support for `static propTypes` and `static defaultProps` syntax, so I recommend that!

**Comment by boygirl** [comment]
hmm, I'll check again

**Pull request merged**
